ci: refactor terraform validation

diff --git a/.github/workflows/terraform-validate-template.yml b/.github/workflows/terraform-validate-template.yml
--- a/.github/workflows/terraform-validate-template.yml
+++ b/.github/workflows/terraform-validate-template.yml
@@ -54,7 +54,13 @@ jobs:
       - name: "Checkout"
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - name: Check Terraform formatting
-        run: terraform fmt -recursive -diff
+        run: |
+          terraform fmt -recursive -diff
+          if [ $? -ne 0 ]; then
+            echo "Terraform formatting failed"
+            echo ::set-output name="Terraform fmt failed"::failed
+            exit 1
+          fi
       - name: Reviewdog suggester (Terraform fmt)
         if: inputs.suggestions && github.event_name == 'pull_request'
         uses: reviewdog/action-suggester@v1
@@ -88,3 +94,9 @@ jobs:
           flags: '--recursive'
           reporter: github-pr-review
           fail_on_error: ${{ inputs.continue-on-error }}
+      - name: check failure
+        if: failure() && inputs.continue-on-error == false
+        run: |
+          echo "Terraform validation failed"
+          echo ::set-output name="Terraform lint failed"::failed
+          exit 1
